### ISSUE TITLE
Change database name in  create_database script for mysql to upper case

### ISSUE THREAD

**Issue by mpujari** [acciente/oacc-db#1]
Make changes to database or schema for all the DB's to have consistent case, i.e. while executing the scripts on Ubuntu for Mysql create_tables.sql fail as the database name in the script is specified as upper case and where as in create_database script we have created the DB with lower case.

Can we check for all other scripts and DB to have database and schema to be consistence naming.

**Comment by mpujari** [comment]
Just realized its enough to make the Mysql database to be case-in-sensitive.

Can we have a note of this some where so that people get to know about this issue or make all the scripts in one case.

**Comment by fspinnenhirn** [comment]
Mahesh, we've just pushed out a release that includes consistent database schema names across all scripts.

Thanks for bringing this to our attention!

**Comment by mpujari** [comment]
:thumbsup: @fspinnenhirn

**Comment by azell** [comment]
One change was missing (`Id` to `ID`):

```
$ diff /tmp/create_user.sql create_user.sql 
29c29
< GRANT SELECT, INSERT, UPDATE, DELETE ON OACCDB.OAC_ResourceExternalId TO `oaccuser`@`localhost`;
---
> GRANT SELECT, INSERT, UPDATE, DELETE ON OACCDB.OAC_ResourceExternalID TO `oaccuser`@`localhost`;
```

This is with `oacc-db-2.0.0-rc.7` and MySQL 5.7.
