### ISSUE TITLE
MySQL 5.7 tables are case-sensitive

### ISSUE THREAD

**Issue by azell** [acciente/oacc-db#3]
The schema refers to `OAC_ResourceExternalID` (note the uppercase `ID`) while the Java code refers to `OAC_ResourceExternalId`.  The oacc-core integration tests fail under MySQL 5.7.16:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: DELETE command denied to user 'oaccuser'@'10.0.2.2' for table 'OAC_ResourceExternalId'
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: SELECT command denied to user 'oaccuser'@'10.0.2.2' for table 'OAC_ResourceExternalId'
```

Will submit a pull request that passes integration tests.

**Comment by adinath-raveendraraj** [comment]
Hi Adam, thank you for your pull request. It is pretty cool that you are running our test suite! One of the things on my todo list to complete the Contributor License Agreement for the OACC project, and setup the workflow to enable a contributor such as yourself to submit a completed CLA. The CLA has been drafted, and is pending finalization. Your pull request provides a reason to bubble it up in priority :)

**Comment by azell** [comment]
Great, please send it over when it is completed.  I had to sign something similar for https://github.com/jersey/jersey so hopefully it will be a quick turnaround.

I had to hack around a bit to get the integration tests to run as I couldn't find a HOWTO:
1. Add MySQL driver dependency to the root pom
2. Fill out src/test/resources/dbconfig_mysql.properties
3. Run mvn -Ddbconfig=dbconfig_mysql.properties test

Did I miss any steps?

**Comment by azell** [comment]
Any progress on the CLA?

**Comment by adinath-raveendraraj** [comment]
Hi Adam, thanks for the ping! Yes, there is progress on the CLA. The CLA was completed and sent to our company lawyer on 11/14/16 for review -- unfortunately she has been really busy. I pinged her in response to your message, and she is expecting to review this week.

**Comment by azell** [comment]
I would also like to replace the `#` comments in the MySQL scripts with the more portable `--`.  Liquibase does not support the former.  Will add to the pull request.

**Comment by adinath-raveendraraj** [comment]
Hi Adam, the CLA document is now available for review. I will let you know when the submission instructions are ready. Needless to say, please **do not** submit the signed CLA via GitHub since it contains personal information.

I am hoping to complete the submission instructions this week, in the meantime you may review the CLA document here: https://github.com/acciente/acciente-cla/blob/master/ACCIENTE-Individual-CLA.pdf

**Comment by adinath-raveendraraj** [comment]
Hi Adam, happy to announce that the CLA submission process has been setup. You can download the CLA and read the submission instructions at https://github.com/acciente/acciente-cla

Please feel free to ping me if you have questions. We are close to wrapping up our development for OACC 2.0.0.rc8 (you can preview the work in the _feature/pluggable-password-encryptor..._ branch in the oacc-core repo).

OACC 2.0.0.rc8 is likely going to become the final OACC 2.0.0 release, I would like to get your changes into OACC 2.0.0.rc8 if possible.

**Comment by azell** [comment]
Hello, I have sent the signed CLA to the listed email address.  If you have any interest in Java code for compressing bcrypt data, please let me know and I can open another pull request.  The bcrypt format is documented at https://github.com/ademarre/binary-mcf.
